### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by apastors** [VictorPelaez/coral-reef-optimization-algorithm#22]
Check the performance and implementation of the main methods to see whether they can be further improved.
At least the `extreme_depredation` method should be checked, but maybe some more.

**Comment by apastors** [comment]
Main points
---
- Make code more readable in general. Maybe even follow a common standard ([pep8](https://www.python.org/dev/peps/pep-0008/))
- I have seen in the code several times something such as ```if opt == "max": ... else: ...```. Maybe we could always minimize either `fitness` or `-fitness` depending on `opt`?
  Something like initializing a variable called `self.opt_multiplier` in `__init__` that equals 1 or -1 depending on `opt` and use it in the `fitness` method. That way we would simplify the rest of the code.

Specific points
---
**Reef Initialization**: Depends on the problem, so a module with different initialization functions should be considered.
  When specifying the mode, the correct function should be imported, which would take care of initialization depending on the mode (variable span for continuous variables, possible values of discrete values, etc...)
 
**Fitness**:
```python
if coral == self.empty_coral:
    continue
```
**Broadcast spawning**: Allow different types of crossover (not only 1 point but _n_). Maybe this is not priority
**Brooding**: One point mutation..? Check carefully.
**Larvae setting**: Big function, I have the feeling this could be implemented a bit more efficiently in general.
**plot_results**: Move this away from the `CRO` class, as it is not part of the algorithm itself. Maybe a different module dedicated to reporting results?

@VictorPelaez  What do you think? Any other ideas?

**Comment by VictorPelaez** [comment]
Maybe we can split this issue. For example:

- "refactoring selector using opt value" (really interesting point and not quite difficult to test)
- "refactoring common standard" (easy issue i think but maybe it is not so high priority)

About Specific points, I think quite the same, open one issue for each. Maybe we can leave this issue as general summary of improvements and refactoring issues. I will open some of them. For example, plot_results function has to be in another module, obviously. 

@apastors what you think?

**Comment by apastors** [comment]
Agree, I will close this issue and create a milestone to group all the issues related to this big one.
