### ISSUE TITLE
Best fitness worsens over time

### ISSUE THREAD

**Issue by apastors** [VictorPelaez/coral-reef-optimization-algorithm#23]
When testing I noticed that the best fitness decreases (see image) and I wonder, could it be that the `depredation` gets rid of the best coral in the reef? The `extreme_depredation` cannot be, as it deletes only corals that are not unique, and up to a certain limit.

![image](https://user-images.githubusercontent.com/8972462/31587741-5caf7e66-b1e7-11e7-844b-f4c29c41ddff.png)

**Comment by VictorPelaez** [comment]
Hi, I reproduced it. Weird, if we comment depredation(), the result is exactly the same! So, it means: 

- is depredation function working and improving each generation?
- I think the bug is inside extremedepredation function because of that

**Comment by VictorPelaez** [comment]
It is not a problem inside extremedepredation(). I insert a print pre function and post function: 

```
pre extremedepredation: 0.982046070461
n=17
post extremedepredation: 0.982046070461
Best-fitness: 0.982046070461 
 85.0% completado 

pre extremedepredation: 0.941700080192
n=18
post extremedepredation: 0.941700080192
Best-fitness: 0.941700080192 
 90.0% completado 
```

best fitness is reduced in n=18 over 20, put it is previously...

**Comment by VictorPelaez** [comment]
Bug detected, it is not REEF[ind] and REEFfitness[ind], It is REEFfitness[[ocup[ind]]...

```
#check if the larva is better than the installed coral
if ( (self.opt=='max') & (larvaefitness[0] > REEFfitness[ocup[ind]])) | ( (self.opt=='min')  & (larvaefitness[0] < REEFfitness[ocup[ind]])): 
                    #settle the larva
                    REEF[ind] = 1
                    REEFpob[ind, :] = larvae[0, :]
                    REEFfitness[ind] = larvaefitness[0]
```
