### ISSUE TITLE
create a opt_multiplier (-1 or 1) with opt argument

### ISSUE THREAD

**Issue by VictorPelaez** [VictorPelaez/coral-reef-optimization-algorithm#32]
One of the main point suggested in Issue #22. 
Using  opt argument, create a self.opt_multiplier (1, -1)

It looks an improvement in 2 functions: 

- budding()

```
        if self.opt=='max': ind = np.argsort(-fitness); 
        else: ind = np.argsort(fitness)    
```

- depredation()
```
        if (self.opt=='max'):
            ind = np.argsort(REEFfitness)
        else: 
            ind = np.argsort(-REEFfitness)
```

@apastors Did your proposal cover anything else? regards

**Comment by apastors** [comment]
Yes that should be it, I'll start this one.

**Comment by VictorPelaez** [comment]
great job! it really simplifies cro functions
