### ISSUE TITLE
Refactoring larvaesetting function

### ISSUE THREAD

**Issue by VictorPelaez** [VictorPelaez/coral-reef-optimization-algorithm#33]
One of the point suggested in Issue #22 is try to simplify larvaesetting() function

Let's focus and analyze this function. I think there are two main parts (maybe just other at the beginning): 

1. larvae occupies empty places: It could be reduced with a function to settle larvaes given positions (it is also used in second part, in each iteration)

```
(REEF, REEFpob, REEFfitness) = self._settle_larvae(REEF, REEFpob, REEFfitness,
                                                           larvae[:len(free), :], larvaefitness[:len(free)], free)
```

2. larvae fight for occupied places: there are you loops inside, one for iter inside larvaes and other for k trials. Second one could be avoid with:

```
for nlarvae in range(Nlarvae):                     
            ind_ks = np.random.permutation(ocup)[:k]            
            if (self.opt=='max'): 
                f = larvaefitness[nlarvae]>REEFfitness[ind_ks];               
            else: 
                f = larvaefitness[nlarvae]<REEFfitness[ind_ks];
                                            
            if np.any(f): 
                ind = np.where(f)[0][0]
                settle_ind = ind_ks[ind]
                (REEF, REEFpob, REEFfitness) = self._settle_larvae(REEF, REEFpob, REEFfitness,
                                                                   larvae[nlarvae, :], larvaefitness[nlarvae], settle_ind)
                #eliminate the place from the occupied ones
                ocup = np.delete(ocup, ind) 
```
I tested and it works fine, but I think, first loop is quite difficult to eliminate because each larvae needs to know occupied places left

Maybe create two separated function for each part, make sense?

One issue I detected is that larvaes go first for empty places and them others fight, make sense? another approach could be decide at the begging which larvae (portion) will fight or not. I is going to reduce code, because you don't need to update the larvae list. What you think @apastors?

Another issue, original code contains at the beginning: 
```
        a = np.random.permutation(Nlarvae)
        larvae = larvae[a, :]
        larvaefitness = larvaefitness[a]
```
Maybe it is not necessary, I mean larvae list is giving in a random way so why permutated them again?

**Comment by apastors** [comment]
I tried point number 2 and the results were the same but it took a bit longer. Maybe using operations such as `np.where` are more expensive than the inner loop (`k` is usually a small number, so looping is not that expensive after all)
