### ISSUE TITLE
Refactor Broadcast spawning

### ISSUE THREAD

**Issue by apastors** [VictorPelaez/coral-reef-optimization-algorithm#36]
Allow different types of crossover (not only 1 point but _n_)

**Comment by VictorPelaez** [comment]
How does it select _n_? another random number between 1 and _L_?
varying over generations?

**Comment by VictorPelaez** [comment]
@apastors I am checking it but it looks fine, I mean mask could contains several ones, so spawners get crossover in several points:

`mask = np.random.randint(2, size=[a,b]) `

for example:

```
[[0 0 0 0 1 0 0 1]] mask
[[4 8 7 6 4 2 5 7]] spawner1
 [[ 4  6  7  9  5  7 10  5]]  spawner2
```
ESlarvae is 
[[ **4  8  7  6**  5  **2  5**  5]
 [ **4  6  7  9**  4  **7 10**  7]]

maybe the error is just the function explanation and description

**Comment by VictorPelaez** [comment]
@apastors I just deleted this code line (don't know which is its purpose...), sorting a mask and the results improve again incredibly faster

```
 mask = np.random.randint(2, size=[a,b])
 mask = np.sort(mask, axis=0) #this one
...
```


![withoutsort](https://user-images.githubusercontent.com/9797745/32133084-22762634-bbd1-11e7-851f-1c9319a5d0b6.png)



```
Best coral:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Best solution: 100.0
Wall time: 27.9 s
```

**Comment by apastors** [comment]
My idea was to allow the user to specify differnt kinds of crossovers (1 point crossover, 2 points crossover, random crossover, which is the one implemented now btw). I don't think it is that important though, there are more important things to do at the moment, so maybe we should close this issue?

**Comment by VictorPelaez** [comment]
Then closed
