### ISSUE TITLE
One example uses the Boston housing prices dataset

### ISSUE THREAD

**Issue by musicinmybrain** [VictorPelaez/coral-reef-optimization-algorithm#64]
**Expected behaviour:**

The Boston housing prices dataset (`sklearn.dataset.load_boston()`) should not be used. Ethical problems identified in its construction have prompted its deprecation in scikit-learn 1.0 and scheduled removal in scikit-learn 1.2.

**Actual behaviour:**

“Example II: feature selection, regression (min mse)” in `example_advanced.py` uses the Boston housing prices dataset.

---

Ideally, this example can be re-implemented using an alternative dataset. If not, it may be necessary to remove it, as it will be broken by scikit-learn 1.2.

**Comment by penguinpee** [comment]
This now blocks the package from being built in Fedora.

**Comment by VictorPelaez** [comment]
remove it in the advanced example ; Release 0.0.5.2
