### ISSUE TITLE
Draft a new release

### ISSUE THREAD

**Issue by firefly-cpp** [VictorPelaez/coral-reef-optimization-algorithm#66]
Several issues have been fixed since the latest release. Thus, please draft a new release (@VictorPelaez).

**Comment by firefly-cpp** [comment]
Issues may not be a proper term. Several improvements were added. Please update a 0.0.6 also to PyPI and create a tag here.

**Comment by firefly-cpp** [comment]
@VictorPelaez,  several changes have been committed since the release of 0.0.5. Thus, publishing the newest version to Pypi may be suitable, especially from the perspective of package maintenance in other ecosystems.

See commits:
#63 #59 #60 #58

**Comment by VictorPelaez** [comment]
https://pypi.org/project/cro/ version 0.0.5.2 is released. @alvaro-ps @musicinmybrain @firefly-cpp 
Thanks!
