### ISSUE TITLE
Fitness decoupling

### ISSUE THREAD

**Issue by apastors** [VictorPelaez/coral-reef-optimization-algorithm#7]
(I'll try and write in English as the whole repo is in English)

One of the main issues that I can see, which is by the way inherited from the Matlab code, is the coupling between the CRO itself and the function it tries to optimize. This can be seen in the `fitness` and `fitness_emptycoral` methods:
```python
        if self.problem_name=='max_ones':
        ...
        if self.problem_name=='feature_selection':
```
This means that these functions should be modified whenever we want to implement a different optimization.
Instead, I would propose that when instantiating the `CRO` object, a `fitness_coral` function is also passed and stored as an attribute. This function would accept an individual of the population as an argument and return its fitness value: 
```python
def compute_fitness(coral):
    ...
    return fitness

CRO(Ngen, N, M, ..., fitness_coral=compute_fitness, ..., verbose=False)
```
The CRO's `fitness` function would just call this `fitness_coral` function (which would depend on the problem to optimize, so we could have `fitness_maxone` for the max-one problem or `fitness_feature_selection` for the feature selection problem) as many times as corals in the reef (we could create another issue to tackle the parallelization of this `fitness` function).

There is also another kind of coupling which is not that obvious, which relates to the kind of population in the reef. In this case, both for the max-ones and the feature selection, corals are just vectors of booleans, but this is specific to some kinds of problems. This is of course out of the scope of this particular issue.

**Comment by VictorPelaez** [comment]
Hola Álvaro!





Sí. es una muy buena idea. Tenía en mente algo así, pero no se como hacer que convivan todas las func fitness... además creo que tenemos que hacerlo más cerrado y sencillo. Es decir, cuando terminemos que se pueda meter una función como parámetro, crear una especie de funciones genéricas (librería de funciones testeadas) para que el usuario no tenga que escribirlas. ¿Te parece?

Efectivamente, creo que luego es más sencillo de paralelizar esa parte! Genial


He abierto una rama llamada feature/fitness_decoupling_7.  lo he solucionado para el max_ones. Hacemos una prueba, ¿puedes bajarte esa rama, y hacer tu un push sobre el repositorio? Si eso funciona, luego cuando terminemos las rama (llamada como la issue) hacemos PR sobre develop. Tendríamos que resolver las funciones para feature selection... para terminar la issue, ¿no?



Abrazo!

________________________________
De: apastors <notifications@github.com>
Enviado: miércoles, 11 de octubre de 2017 22:12
Para: VictorPelaez/coral-reef-optimization-algorithm
Cc: Subscribed
Asunto: [VictorPelaez/coral-reef-optimization-algorithm] Fitness decoupling (#7)


(I'll try and write in English as the whole repo is in English)

One of the main issues that I can see, which is by the way inherited from the Matlab code, is the coupling between the CRO itself and the function it tries to optimize. This can be seen in the fitness and fitness_emptycoral methods:

        if self.problem_name=='max_ones':
        ...
        if self.problem_name=='feature_selection':

This would mean that this functions should be modified whenever we want to implement a different optimization.
Instead, I would propose that when instantiating the CRO object, a fitness_individual function is also passed and stored as an attribute. This function would accept an individual of the population as an argument and return its fitness value:

def compute_fitness(individual):
    ...
    return fitness

CRO(Ngen, N, M, ..., fitness_individual=compute_fitness, ..., verbose=False)

The CRO's fitness function would just call this fitness_individual function as many times as individuals in the reef (we could create another issue to tackle the parallelization of this fitness function).

There is also another kind of coupling which is not that obvious, which relates to the kind of population in the reef. In this case, both for the max-ones and the feature selection, individuals in the population are just a vector of booleans, but this is specific to some kinds of problems. This is of course out of the scope of this particular issue.
